# Generated by Django 5.2.1 on 2025-05-12 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название темы')),
                ('type', models.CharField(choices=[('light', 'Светлая'), ('dark', 'Тёмная'), ('colorful', 'Цветная'), ('minimalist', 'Минималистичная'), ('professional', 'Профессиональная'), ('creative', 'Креативная')], max_length=20, verbose_name='Тип темы')),
                ('primary_color', models.CharField(default='#007bff', max_length=20, verbose_name='Основной цвет')),
                ('secondary_color', models.CharField(default='#6c757d', max_length=20, verbose_name='Вторичный цвет')),
                ('background_color', models.CharField(default='#ffffff', max_length=20, verbose_name='Цвет фона')),
                ('text_color', models.CharField(default='#212529', max_length=20, verbose_name='Цвет текста')),
                ('css_file', models.FileField(blank=True, null=True, upload_to='portfolio_themes/', verbose_name='CSS файл')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Премиум тема')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='theme_previews/', verbose_name='Изображение для предпросмотра')),
            ],
            options={
                'verbose_name': 'Тема портфолио',
                'verbose_name_plural': 'Темы портфолио',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания подписки'),
        ),
        migrations.CreateModel(
            name='PortfolioSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.CharField(choices=[('standard', 'Стандартный'), ('modern', 'Современный'), ('classic', 'Классический'), ('creative', 'Креативный')], default='standard', max_length=20, verbose_name='Макет')),
                ('show_skills', models.BooleanField(default=True, verbose_name='Показывать навыки')),
                ('show_education', models.BooleanField(default=True, verbose_name='Показывать образование')),
                ('show_certificates', models.BooleanField(default=True, verbose_name='Показывать сертификаты')),
                ('show_achievements', models.BooleanField(default=True, verbose_name='Показывать достижения')),
                ('show_contact_info', models.BooleanField(default=False, verbose_name='Показывать контактную информацию')),
                ('custom_css', models.TextField(blank=True, verbose_name='Пользовательский CSS')),
                ('custom_domain', models.CharField(blank=True, max_length=100, verbose_name='Пользовательский домен')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_settings', to=settings.AUTH_USER_MODEL)),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.portfoliotheme')),
            ],
            options={
                'verbose_name': 'Настройки портфолио',
                'verbose_name_plural': 'Настройки портфолио',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='Код активации')),
                ('duration_days', models.PositiveIntegerField(default=30, verbose_name='Длительность подписки (дней)')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Использован')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Код подписки',
                'verbose_name_plural': 'Коды подписки',
            },
        ),
    ]
