# Generated by Django 5.2.1 on 2025-05-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='enable_2fa',
            field=models.BooleanField(default=False, help_text='При включенной опции вам потребуется вводить код подтверждения при входе.', verbose_name='Включить двухфакторную аутентификацию'),
        ),
    ]
