# Generated by Django 5.2.1 on 2025-05-12 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_portfoliotheme_customuser_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время просмотра')),
                ('referrer', models.URLField(blank=True, max_length=500, verbose_name='Источник перехода')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to=settings.AUTH_USER_MODEL)),
                ('viewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewed_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Просмотр профиля',
                'verbose_name_plural': 'Просмотры профиля',
                'indexes': [models.Index(fields=['profile', 'timestamp'], name='users_profi_profile_4b44ab_idx')],
            },
        ),
    ]
