# Generated by Django 5.2.1 on 2025-05-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profileview'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliosettings',
            name='subdomain',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Субдомен'),
        ),
        migrations.AddField(
            model_name='portfoliosettings',
            name='use_subdomain',
            field=models.BooleanField(default=False, verbose_name='Использовать субдомен'),
        ),
    ]
