# Generated by Django 5.2.1 on 2025-05-14 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_portfoliosettings_subdomain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('template_type', models.CharField(choices=[('basic', 'Базовый'), ('professional', 'Профессиональный'), ('creative', 'Креативный'), ('academic', 'Академический'), ('technical', 'Технический')], max_length=20, verbose_name='Тип шаблона')),
                ('color_scheme', models.CharField(choices=[('blue', 'Синяя'), ('green', 'Зеленая'), ('red', 'Красная'), ('purple', 'Фиолетовая'), ('orange', 'Оранжевая'), ('black', 'Черно-белая'), ('custom', 'Пользовательская')], default='blue', max_length=20, verbose_name='Цветовая схема')),
                ('primary_color', models.CharField(default='#3498db', max_length=20, verbose_name='Основной цвет')),
                ('secondary_color', models.CharField(default='#2c3e50', max_length=20, verbose_name='Вторичный цвет')),
                ('accent_color', models.CharField(default='#e74c3c', max_length=20, verbose_name='Акцентный цвет')),
                ('background_color', models.CharField(default='#ffffff', max_length=20, verbose_name='Цвет фона')),
                ('text_color', models.CharField(default='#333333', max_length=20, verbose_name='Цвет текста')),
                ('font_family', models.CharField(default='Arial, sans-serif', max_length=100, verbose_name='Шрифт')),
                ('header_font', models.CharField(blank=True, max_length=100, verbose_name='Шрифт заголовков')),
                ('css_template', models.TextField(blank=True, verbose_name='Шаблон CSS')),
                ('html_template', models.TextField(blank=True, verbose_name='Шаблон HTML')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='resume_templates/', verbose_name='Изображение для предпросмотра')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Премиум шаблон')),
                ('is_editable', models.BooleanField(default=True, verbose_name='Редактируемый шаблон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Шаблон резюме',
                'verbose_name_plural': 'Шаблоны резюме',
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'Студент'), ('teacher', 'Преподаватель'), ('admin', 'Администратор'), ('support', 'Специалист поддержки')], default='student', max_length=10, verbose_name='Тип пользователя'),
        ),
        migrations.CreateModel(
            name='UserResumeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(blank=True, max_length=20, verbose_name='Основной цвет')),
                ('secondary_color', models.CharField(blank=True, max_length=20, verbose_name='Вторичный цвет')),
                ('accent_color', models.CharField(blank=True, max_length=20, verbose_name='Акцентный цвет')),
                ('background_color', models.CharField(blank=True, max_length=20, verbose_name='Цвет фона')),
                ('text_color', models.CharField(blank=True, max_length=20, verbose_name='Цвет текста')),
                ('font_family', models.CharField(blank=True, max_length=100, verbose_name='Шрифт')),
                ('custom_css', models.TextField(blank=True, verbose_name='Пользовательский CSS')),
                ('show_profile_image', models.BooleanField(default=True, verbose_name='Показывать фото профиля')),
                ('show_skills', models.BooleanField(default=True, verbose_name='Показывать навыки')),
                ('show_education', models.BooleanField(default=True, verbose_name='Показывать образование')),
                ('show_projects', models.BooleanField(default=True, verbose_name='Показывать проекты')),
                ('show_certificates', models.BooleanField(default=True, verbose_name='Показывать сертификаты')),
                ('show_achievements', models.BooleanField(default=True, verbose_name='Показывать достижения')),
                ('show_contact_info', models.BooleanField(default=True, verbose_name='Показывать контактную информацию')),
                ('max_projects', models.PositiveSmallIntegerField(default=5, verbose_name='Максимальное количество проектов')),
                ('max_certificates', models.PositiveSmallIntegerField(default=5, verbose_name='Максимальное количество сертификатов')),
                ('max_achievements', models.PositiveSmallIntegerField(default=5, verbose_name='Максимальное количество достижений')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.resumetemplate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройки резюме',
                'verbose_name_plural': 'Настройки резюме',
            },
        ),
    ]
