# Generated by Django 5.2.1 on 2025-05-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_resumetemplate_alter_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio_en',
            field=models.TextField(blank=True, null=True, verbose_name='Биография'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Биография'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Биография'),
        ),
        migrations.AddField(
            model_name='portfoliotheme',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название темы'),
        ),
        migrations.AddField(
            model_name='portfoliotheme',
            name='name_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Название темы'),
        ),
        migrations.AddField(
            model_name='portfoliotheme',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название темы'),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='description_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название шаблона'),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='name_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Название шаблона'),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название шаблона'),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Название навыка'),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_kk',
            field=models.CharField(max_length=50, null=True, verbose_name='Название навыка'),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название навыка'),
        ),
    ]
