# Generated by Django 5.2.1 on 2025-05-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_bio_en_customuser_bio_kk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='faculty_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Факультет'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='faculty_kk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Факультет'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='faculty_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Факультет'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='specialization_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Специализация'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='specialization_kk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Специализация'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='specialization_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Специализация'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='university_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Учебное заведение'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='university_kk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Учебное заведение'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='university_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Учебное заведение'),
        ),
    ]
