# Generated by Django 5.2.1 on 2025-05-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_faculty_en_customuser_faculty_kk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='custom_url',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Уникальный URL'),
        ),
    ]
