# Generated by Django 4.2.7 on 2025-05-09 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliocomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='portfoliocomment',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='portfolio.portfolio', verbose_name='Портфолио'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='education',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='portfolio.portfolio', verbose_name='Портфолио'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='portfolio.portfolio', verbose_name='Портфолио'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='portfolio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='about', to='portfolio.portfolio', verbose_name='Портфолио'),
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('portfolio', 'name')},
        ),
    ] 