# Generated by Django 4.2.7 on 2025-05-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='theme',
            field=models.CharField(default='default', max_length=50, verbose_name='Тема оформления'),
        ),
    ]
