# Generated by Django 5.2.1 on 2025-05-12 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_projectpost_projectcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время просмотра')),
                ('referrer', models.URLField(blank=True, max_length=500, verbose_name='Источник перехода')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='portfolio.project')),
                ('viewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewed_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Просмотр проекта',
                'verbose_name_plural': 'Просмотры проекта',
                'indexes': [models.Index(fields=['project', 'timestamp'], name='portfolio_p_project_6b52bf_idx')],
            },
        ),
    ]
