# Generated by Django 5.2.1 on 2025-05-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_projectview'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='category',
            field=models.CharField(blank=True, max_length=100, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='date_received',
            field=models.DateField(blank=True, null=True, verbose_name='Дата получения'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='achievements_images/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='issuing_organization',
            field=models.CharField(blank=True, max_length=100, verbose_name='Выдавшая организация'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='credential_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID сертификата'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='credential_url',
            field=models.URLField(blank=True, verbose_name='URL для проверки'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='certificates_images/', verbose_name='Изображение сертификата'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issuing_organization',
            field=models.CharField(blank=True, max_length=100, verbose_name='Выдавшая организация'),
        ),
    ]
