# Generated by Django 5.2.1 on 2025-05-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_achievement_category_achievement_date_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='category_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='category_kk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='category_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='description_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='issuing_organization_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Выдавшая организация'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='issuing_organization_kk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Выдавшая организация'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='issuing_organization_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Выдавшая организация'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='organizer_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Организатор'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='organizer_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Организатор'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='organizer_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Организатор'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='title_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='description_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issuer_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Выдан'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issuer_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Выдан'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issuer_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Выдан'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issuing_organization_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Выдавшая организация'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issuing_organization_kk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Выдавшая организация'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issuing_organization_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Выдавшая организация'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='title_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_kk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Используемые технологии'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies_kk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Используемые технологии'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Используемые технологии'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Текст комментария'),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='text_kk',
            field=models.TextField(null=True, verbose_name='Текст комментария'),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст комментария'),
        ),
        migrations.AddField(
            model_name='projectpost',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='projectpost',
            name='content_kk',
            field=models.TextField(null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='projectpost',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='review',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Текст отзыва'),
        ),
        migrations.AddField(
            model_name='review',
            name='text_kk',
            field=models.TextField(null=True, verbose_name='Текст отзыва'),
        ),
        migrations.AddField(
            model_name='review',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст отзыва'),
        ),
    ]
