# Generated by Django 5.2.1 on 2025-05-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoTranslatedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=100, verbose_name='Тип контента')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID объекта')),
                ('field_name', models.CharField(max_length=100, verbose_name='Название поля')),
                ('source_language', models.CharField(max_length=10, verbose_name='Исходный язык')),
                ('translations', models.JSONField(default=dict, verbose_name='Переводы')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Автоматический перевод',
                'verbose_name_plural': 'Автоматические переводы',
                'unique_together': {('content_type', 'object_id', 'field_name', 'source_language')},
            },
        ),
        migrations.CreateModel(
            name='TranslationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.TextField(verbose_name='Исходный текст')),
                ('source_language', models.CharField(max_length=10, verbose_name='Исходный язык')),
                ('target_language', models.CharField(max_length=10, verbose_name='Целевой язык')),
                ('translated_text', models.TextField(verbose_name='Переведенный текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Кэш перевода',
                'verbose_name_plural': 'Кэш переводов',
                'indexes': [models.Index(fields=['source_language', 'target_language'], name='translator__source__871760_idx')],
                'unique_together': {('source_text', 'source_language', 'target_language')},
            },
        ),
    ]
