"""
Django settings for studfolio project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-REPLACE_WITH_YOUR_SECRET_KEY'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    
    # Third-party apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'crispy_forms',
    'crispy_bootstrap5',
    
    # Custom apps
    'users',
    'portfolio',
    'translator',
    'support',
]

# Crispy Forms settings
CRISPY_TEMPLATE_PACK = 'bootstrap5'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'studfolio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'studfolio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'

# Добавляем доступные языки (более 20 из списка)
LANGUAGES = [
    ('ru', 'Русский'),
    ('en', 'English'),
    ('zh-hans', '简体中文'),  # Chinese Simplified
    ('es', 'Español'),       # Spanish
    ('ja', '日本語'),         # Japanese
    ('de', 'Deutsch'),       # German
    ('fr', 'Français'),      # French
    ('pt', 'Português'),     # Portuguese
    ('ar', 'العربية'),       # Arabic
    ('ko', '한국어'),         # Korean
    ('it', 'Italiano'),      # Italian
    ('nl', 'Nederlands'),    # Dutch
    ('zh-hant', '繁體中文'),  # Chinese Traditional
    ('tr', 'Türkçe'),        # Turkish
    ('hi', 'हिन्दी'),         # Hindi
    ('pl', 'Polski'),        # Polish
    ('fa', 'فارسی'),         # Farsi/Persian
    ('ms', 'Bahasa Melayu'), # Malay
    ('sv', 'Svenska'),       # Swedish
    ('th', 'ไทย'),           # Thai
    ('id', 'Bahasa Indonesia'), # Indonesian
    ('el', 'Ελληνικά'),      # Greek
    ('no', 'Norsk'),         # Norwegian
    ('cs', 'Čeština'),       # Czech
    ('he', 'עברית'),         # Hebrew
    ('kk', 'Қазақша'),       # Kazakh
]

TIME_ZONE = 'UTC'

USE_I18N = True

# Директории с файлами локализации
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication settings
AUTH_USER_MODEL = 'users.CustomUser'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1

# Настройки django-allauth (обновленные)
# ACCOUNT_AUTHENTICATION_METHOD = 'username_email' # Устарело
# ACCOUNT_EMAIL_REQUIRED = True # Устарело
# ACCOUNT_USERNAME_REQUIRED = True # Устарело
# ACCOUNT_LOGIN_ATTEMPTS_LIMIT = 5 # Устарело
# ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT = 300 # Устарело

ACCOUNT_EMAIL_VERIFICATION = 'optional' # Верификация email: 'mandatory', 'optional', 'none'
ACCOUNT_UNIQUE_EMAIL = True # Требовать уникальный email

# Обязательные поля при регистрации.
# По умолчанию allauth требует username и email, если они есть в модели пользователя.
# Это поле больше для кастомизации формы регистрации через ACCOUNT_SIGNUP_FORM_CLASS,
# чтобы указать, какие поля из формы обязательны.
# Для стандартного поведения можно не указывать, если USERNAME_FIELD и EMAIL_FIELD определены.
ACCOUNT_SIGNUP_FIELDS = {
    # 'username': True, # allauth автоматически делает username обязательным, если он есть
    # 'email': True,    # allauth автоматически делает email обязательным
    'password': True, # Это укажет allauth, что поле пароля (и его подтверждение) должно быть в форме
}
# Если быть точным как в предупреждении (с явным указанием полей):
# ACCOUNT_SIGNUP_FIELDS = {
#     'username': True, # Обязательно
#     'email': True,    # Обязательно
#     # allauth сам добавит password2 если password есть и ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE было бы True
#     # Для явного контроля формы, если бы мы кастомизировали SignupForm, можно было бы указать password1, password2
# }
# Для простоты и если стандартная форма allauth используется, указания 'password': True должно быть достаточно,
# allauth подхватит и создаст два поля для пароля.

# ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = True # Требовать ввод пароля дважды при регистрации # <-- Устарело, закомментируем

# Настройка ограничения попыток входа (замена для ACCOUNT_LOGIN_ATTEMPTS_LIMIT/TIMEOUT)
ACCOUNT_RATE_LIMITS = {
    'login_failed': '5/5m',  # 5 попыток за 5 минут
    # Можно добавить другие ключи, например, 'signup': '10/h'
}

# Поля модели пользователя (allauth обычно определяет их автоматически)
ACCOUNT_USER_MODEL_USERNAME_FIELD = 'username' # По умолчанию 'username'
ACCOUNT_USER_MODEL_EMAIL_FIELD = 'email'       # По умолчанию 'email'

# URL-адреса для перенаправления
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Если вы используете кастомную форму регистрации, укажите ее здесь
ACCOUNT_SIGNUP_FORM_CLASS = None # Например, 'users.forms.CustomSignupForm'

# Email backend для разработки (вывод в консоль)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
